# For more information: https://laravel.com/docs/sail
services:
    mars-rover:
        build:
            context: docker/php/apache
            dockerfile: Dockerfile
        container_name: mars-rover
        image: 'mars-rover:latest'
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - mars-rover
        depends_on:
            - rabbitmq
            - redis

    rabbitmq-consumer:
        build:
            context: docker/php/cli
            dockerfile: Dockerfile
        container_name: rabbitmq-consumer
        image: 'mars-rover-consumer:latest'
        ports:
            - '81:81'
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        networks:
            - mars-rover
        depends_on:
            - redis
            - rabbitmq

    redis:
        image: 'redis:7-alpine'
        platform: linux/amd64
        container_name: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - mars-rover
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    rabbitmq:
        image: 'rabbitmq:management-alpine'
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - mars-rover


networks:
    mars-rover:
        driver: bridge
volumes:
    redis:
        driver: local
